<a href="https://colab.research.google.com/github/Bunny825/Final_Project_SE/blob/main/medical_expenses.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
data=pd.read_csv("/content/insurance.csv")
data.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [ ]:
data.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
data["sex"].replace({"female":0,"male":1},inplace=True)

<ipython-input-119-521ecbee1df6>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["sex"].replace({"female":0,"male":1},inplace=True)
<ipython-input-119-521ecbee1df6>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["sex"].replace({"female":0,"male":1},inplace=True)


In [ ]:
data["smoker"].replace({"no":0,"yes":1},inplace=True)


<ipython-input-120-d199d8dbbdf8>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["smoker"].replace({"no":0,"yes":1},inplace=True)
<ipython-input-120-d199d8dbbdf8>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["smoker"].replace({"no":0,"yes":1},inplace=True)


In [ ]:
data["region"].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [ ]:
data["region"].replace({"southeast":1,"southwest":2,"northwest":3,"northeast":4},inplace=True)

<ipython-input-122-e33d1cc6a558>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["region"].replace({"southeast":1,"southwest":2,"northwest":3,"northeast":4},inplace=True)
<ipython-input-122-e33d1cc6a558>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["region"].replace({"southeast":1,"so

In [ ]:
data.head()

age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       2  16884.92400
1   18    1  33.770         1       0       1   1725.55230
2   28    1  33.000         3       0       1   4449.46200
3   33    1  22.705         0       0       3  21984.47061
4   32    1  28.880         0       0       3   3866.85520

In [ ]:
from sklearn.model_selection import train_test_split
x=data.iloc[:,:-1]
y=data.iloc[:,-1]


In [ ]:

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x=scaler.fit_transform(x)
print(x)

[[-1.43876426 -1.0105187  -0.45332    -0.90861367  1.97058663 -0.40287427]
 [-1.50996545  0.98959079  0.5096211  -0.07876719 -0.5074631  -1.28800691]
 [-0.79795355  0.98959079  0.38330685  1.58092576 -0.5074631  -1.28800691]
 ...
 [-1.50996545 -1.0105187   1.0148781  -0.90861367 -0.5074631  -1.28800691]
 [-1.29636188 -1.0105187  -0.79781341 -0.90861367 -0.5074631  -0.40287427]
 [ 1.55168573 -1.0105187  -0.26138796 -0.90861367  1.97058663  0.48225837]]


In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(1070, 6) (268, 6) (1070,) (268,)


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras import backend as K
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2

def r2_score(y_true, y_pred):
    ss_res = K.sum(K.square(y_true - y_pred))
    ss_tot = K.sum(K.square(y_true - K.mean(y_true)))
    return 1 - ss_res / (ss_tot + K.epsilon())

model = Sequential()
model.add(Dense(128, activation="relu", input_dim=6, kernel_regularizer=l2(0.001)))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(64, activation="relu", kernel_regularizer=l2(0.001)))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(32, activation="relu", kernel_regularizer=l2(0.001)))
model.add(BatchNormalization())
model.add(Dropout(0.1))

model.add(Dense(16, activation="relu"))
model.add(Dense(8, activation="relu"))
model.add(Dense(1))

model.compile(
    optimizer=Adam(learning_rate=0.0005),
    loss='mean_squared_error',
    metrics=[r2_score, 'mae']
)

early_stopping = EarlyStopping(monitor='val_r2_score', patience=10, mode='max', restore_best_weights=True)

history = model.fit(
    x_train, y_train,
    validation_data=(x_test, y_test),
    epochs=100,
    batch_size=32,
    callbacks=[early_stopping]
)


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 320895040.0000 - mae: 13331.9658 - r2_score: -1.3623 - val_loss: 315342848.0000 - val_mae: 12851.6250 - val_r2_score: -1.2165
Epoch 2/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 322198624.0000 - mae: 13237.9189 - r2_score: -1.2594 - val_loss: 315329184.0000 - val_mae: 12851.3770 - val_r2_score: -1.2164
Epoch 3/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 325271488.0000 - mae: 13385.3711 - r2_score: -1.3517 - val_loss: 315297632.0000 - val_mae: 12850.8408 - val_r2_score: -1.2162
Epoch 4/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 335111744.0000 - mae: 13498.1592 - r2_score: -1.2686 - val_loss: 315233440.0000 - val_mae: 12849.7705 - val_r2_score: -1.2157
Epoch 5/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 336941472.0000 - mae: 13628.3369 - r2_score: -1.3334 - val_loss: 315134496.0000 - val_mae: 12848.0996 - val_r2_score: -1.2151
Epoch 6/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 320026944.0000 

In [ ]:
import pickle

pickle.dump(scaler,open("charges_scaler.sav","wb"))

model.save("charges_model.h5")

In [ ]:
input=np.asarray([53,0,28.1,3,0,2])
input=scaler.transform([input])
model.predict(input)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step


array([[12100.822]], dtype=float32)